# Generated by Django 3.2.8 on 2021-11-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор фильма')),
                ('genre', models.CharField(max_length=50, verbose_name='жанр фильма')),
                ('article_text', models.TextField(verbose_name='текст фильма')),
                ('date', models.DateTimeField(verbose_name='дата фильма')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoweb.article')),
            ],
        ),
    ]
